# Generated by Django 2.1.3 on 2018-12-01 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wordplease', '0005_auto_20181129_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='blog',
            name='post',
        ),
        migrations.AddField(
            model_name='blog',
            name='post',
            field=models.ManyToManyField(to='wordplease.Post'),
        ),
    ]
