# Generated by Django 2.1.3 on 2018-12-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordplease', '0006_auto_20181201_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=models.ManyToManyField(blank=True, to='wordplease.Post'),
        ),
    ]
